import {
  DollarSign,
  ShoppingCart,
  PiggyBank,
  Utensils,
  Home,
  Droplets,
  Flame,
  Wifi,
  Bus,
  HeartPulse,
  GraduationCap,
  Film,
  ShoppingBag,
  Shirt,
  Wrench,
  Hammer,
  ShieldCheck,
  Dog,
  Plane,
  Sparkles,
  Pin,
  Zap,
  TrendingUp,
  Repeat,
  Tag,
  Layers,
  Landmark
} from 'lucide-react';
import { EventStatus, EventType, IncomeEventCategory, ExpenseEventCategory, InvestmentEventCategory } from '../../../shared/enums/index.js';

const INCOME_CATEGORY_META = {
  [IncomeEventCategory.SALARY]: { icon: DollarSign, color: '#10b981', bg: 'rgba(16, 185, 129, 0.15)' },
  [IncomeEventCategory.MEAL_ALLOWANCE]: { icon: Utensils, color: '#f59e0b', bg: 'rgba(245, 158, 11, 0.15)' },
  [IncomeEventCategory.BONUS]: { icon: Sparkles, color: '#8b5cf6', bg: 'rgba(139, 92, 246, 0.15)' },
  [IncomeEventCategory.FREELANCE]: { icon: Zap, color: '#06b6d4', bg: 'rgba(6, 182, 212, 0.15)' },
  [IncomeEventCategory.INVESTMENT_RETURN]: { icon: TrendingUp, color: '#3b82f6', bg: 'rgba(59, 130, 246, 0.15)' },
  [IncomeEventCategory.RECURRING_INCOME]: { icon: Repeat, color: '#14b8a6', bg: 'rgba(20, 184, 166, 0.15)' },
  [IncomeEventCategory.OTHER]: { icon: Tag, color: '#94a3b8', bg: 'rgba(148, 163, 184, 0.15)' }
};

const EXPENSE_CATEGORY_META = {
  [ExpenseEventCategory.FOOD]: { icon: Utensils, color: '#f59e0b', bg: 'rgba(245, 158, 11, 0.15)' },
  [ExpenseEventCategory.RENT]: { icon: Home, color: '#3b82f6', bg: 'rgba(59, 130, 246, 0.15)' },
  [ExpenseEventCategory.ELECTRICITY]: { icon: Zap, color: '#eab308', bg: 'rgba(234, 179, 8, 0.15)' },
  [ExpenseEventCategory.WATER]: { icon: Droplets, color: '#06b6d4', bg: 'rgba(6, 182, 212, 0.15)' },
  [ExpenseEventCategory.GAS]: { icon: Flame, color: '#f97316', bg: 'rgba(249, 115, 22, 0.15)' },
  [ExpenseEventCategory.COMMUNICATIONS]: { icon: Wifi, color: '#8b5cf6', bg: 'rgba(139, 92, 246, 0.15)' },
  [ExpenseEventCategory.TRANSPORTATION]: { icon: Bus, color: '#10b981', bg: 'rgba(16, 185, 129, 0.15)' },
  [ExpenseEventCategory.HEALTH]: { icon: HeartPulse, color: '#ef4444', bg: 'rgba(239, 68, 68, 0.15)' },
  [ExpenseEventCategory.EDUCATION]: { icon: GraduationCap, color: '#6366f1', bg: 'rgba(99, 102, 241, 0.15)' },
  [ExpenseEventCategory.ENTERTAINMENT]: { icon: Film, color: '#a855f7', bg: 'rgba(168, 85, 247, 0.15)' },
  [ExpenseEventCategory.SHOPPING]: { icon: ShoppingBag, color: '#f43f5e', bg: 'rgba(244, 63, 94, 0.15)' },
  [ExpenseEventCategory.CLOTHING]: { icon: Shirt, color: '#14b8a6', bg: 'rgba(20, 184, 166, 0.15)' },
  [ExpenseEventCategory.CARMAINTENANCE]: { icon: Wrench, color: '#f97316', bg: 'rgba(249, 115, 22, 0.15)' },
  [ExpenseEventCategory.HOUSE]: { icon: Hammer, color: '#84cc16', bg: 'rgba(132, 204, 22, 0.15)' },
  [ExpenseEventCategory.ENSURANCE]: { icon: ShieldCheck, color: '#0ea5e9', bg: 'rgba(14, 165, 233, 0.15)' },
  [ExpenseEventCategory.PETS]: { icon: Dog, color: '#d97706', bg: 'rgba(217, 119, 6, 0.15)' },
  [ExpenseEventCategory.TRAVEL]: { icon: Plane, color: '#38bdf8', bg: 'rgba(56, 189, 248, 0.15)' },
  [ExpenseEventCategory.PERSONAL_CARE]: { icon: Sparkles, color: '#ec4899', bg: 'rgba(236, 72, 153, 0.15)' },
  [ExpenseEventCategory.SERVICES]: { icon: Pin, color: '#64748b', bg: 'rgba(100, 116, 139, 0.15)' },
  [ExpenseEventCategory.OTHER]: { icon: Tag, color: '#94a3b8', bg: 'rgba(148, 163, 184, 0.15)' }
};

const INVESTMENT_CATEGORY_META = {
  [InvestmentEventCategory.SAVINGS]: { icon: PiggyBank, color: '#8b5cf6', bg: 'rgba(139, 92, 246, 0.15)' },
  [InvestmentEventCategory.STOCKS]: { icon: TrendingUp, color: '#3b82f6', bg: 'rgba(59, 130, 246, 0.15)' },
  [InvestmentEventCategory.FUNDS]: { icon: Layers, color: '#06b6d4', bg: 'rgba(6, 182, 212, 0.15)' },
  [InvestmentEventCategory.REAL_ESTATE]: { icon: Landmark, color: '#10b981', bg: 'rgba(16, 185, 129, 0.15)' },
  [InvestmentEventCategory.CRYPTO]: { icon: Zap, color: '#f59e0b', bg: 'rgba(245, 158, 11, 0.15)' },
  [InvestmentEventCategory.ASSETS]: { icon: Sparkles, color: '#ec4899', bg: 'rgba(236, 72, 153, 0.15)' },
  [InvestmentEventCategory.OTHER]: { icon: Tag, color: '#94a3b8', bg: 'rgba(148, 163, 184, 0.15)' }
};

export const EVENT_MODAL_CONFIG = {
  income: {
    accent: '#10b981',
    icon: DollarSign,
    eventType: EventType.INCOME,
    categoryMeta: INCOME_CATEGORY_META,
    categoryDefault: IncomeEventCategory.SALARY,
    categoryLegacyMap: null,
    defaultStatus: EventStatus.PENDING,
    useBreakdown: true,
    showInitialTarget: false,
    showIsExternal: false,
    includeSnakeObligation: true,
    subtitleKey: 'timeline.incomes',
    subtitleFallback: 'Entradas',
    titleKeys: {
      newKey: 'modal.newIncome', newFallback: 'Nova Entrada',
      editKey: 'modal.editIncome', editFallback: 'Editar Entrada',
      addKey: 'modal.addIncome', addFallback: 'Adicionar Entrada'
    },
    titleLabelKey: 'modal.incomeTitleLabel',
    titleLabelFallback: 'Título / Descrição *',
    titlePlaceholderKey: 'modal.incomeTitlePlaceholder',
    titlePlaceholderFallback: 'Ex: Salário Mensal, Freelance, Bónus, Dividendos...',
    translationPrefix: 'incomeCategories',
    amountLabelKey: 'modal.incomeAmountLabel',
    amountLabelFallback: 'Valor a Receber (€) *',
    amountBg: 'rgba(16, 185, 129, 0.08)',
    dayLabelFallback: 'Dia de Recebimento',
    automaticLabelFallback: 'Recebimento Automático',
    submitBg: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    submitBorder: '#10b981',
    submitShadow: '0 4px 14px rgba(16, 185, 129, 0.35)',
    submitText: '#ffffff'
  },
  expense: {
    accent: '#f43f5e',
    icon: ShoppingCart,
    eventType: EventType.EXPENSE,
    categoryMeta: EXPENSE_CATEGORY_META,
    categoryDefault: ExpenseEventCategory.OTHER,
    categoryLegacyMap: null,
    defaultStatus: EventStatus.PENDING,
    useBreakdown: true,
    showInitialTarget: false,
    showIsExternal: false,
    includeSnakeObligation: false,
    subtitleKey: 'timeline.expenses',
    subtitleFallback: 'Despesas',
    titleKeys: {
      newKey: 'modal.newExpense', newFallback: 'Nova Despesa',
      editKey: 'modal.editExpense', editFallback: 'Editar Despesa',
      addKey: 'modal.addExpense', addFallback: 'Adicionar Despesa'
    },
    titleLabelKey: 'modal.expenseTitleLabel',
    titleLabelFallback: 'Descrição da Despesa *',
    titlePlaceholderKey: 'modal.expenseTitlePlaceholder',
    titlePlaceholderFallback: 'Ex: Renda / Aluguel, Supermercado, Eletricidade, Carro...',
    translationPrefix: 'expenseCategories',
    amountLabelKey: 'modal.expenseAmountLabel',
    amountLabelFallback: 'Valor da Despesa (€) *',
    amountBg: 'rgba(244, 63, 94, 0.08)',
    dayLabelFallback: 'Dia de Vencimento',
    automaticLabelFallback: 'Débito / Pagamento Automático',
    submitBg: '#f43f5e',
    submitBorder: '#f43f5e',
    submitShadow: undefined,
    submitText: undefined
  },
  investment: {
    accent: '#8b5cf6',
    icon: PiggyBank,
    eventType: EventType.INVESTMENT,
    categoryMeta: INVESTMENT_CATEGORY_META,
    categoryDefault: InvestmentEventCategory.SAVINGS,
    categoryLegacyMap: {
      investimento_poupanca: InvestmentEventCategory.SAVINGS,
      investimento_patrimonio: InvestmentEventCategory.ASSETS,
      investimento_outros: InvestmentEventCategory.OTHER
    },
    defaultStatus: EventStatus.PLANNED,
    useBreakdown: false,
    showInitialTarget: true,
    showIsExternal: true,
    includeSnakeObligation: false,
    subtitleKey: 'timeline.investments',
    subtitleFallback: 'Investimentos',
    titleKeys: {
      newKey: 'modal.newInvestment', newFallback: 'Novo Investimento',
      editKey: 'modal.editInvestment', editFallback: 'Editar Investimento',
      addKey: 'modal.addInvestment', addFallback: 'Adicionar Investimento'
    },
    titleLabelKey: 'modal.investmentTitleLabel',
    titleLabelFallback: 'Título / Descrição *',
    titlePlaceholderKey: 'modal.investmentTitlePlaceholder',
    titlePlaceholderFallback: 'Ex: Poupança, Ações, Fundos ETF, Cripto...',
    translationPrefix: 'investmentCategories',
    amountLabelKey: 'modal.monthlyInvestmentAmount',
    amountLabelFallback: 'Aporte Mensal / Valor (€) *',
    amountBg: undefined,
    dayLabelFallback: 'Dia de Aplicação / Vencimento',
    automaticLabelFallback: 'Aporte / Débito Automático',
    submitBg: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)',
    submitBorder: '#8b5cf6',
    submitShadow: '0 4px 14px rgba(139, 92, 246, 0.35)',
    submitText: '#ffffff'
  }
};